apiVersion: apps/v1
kind: Deployment
metadata:
  name: word-counter-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: word-counter
  template:
    metadata:
      labels:
        app: word-counter
    spec:
      containers:
      - name: word-counter-container
        image: abhilashkaluwala/word-counter  